# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, null=True)),
                ('title', models.CharField(max_length=225, null=True)),
                ('description', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, null=True)),
                ('title', models.CharField(max_length=225, null=True)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.image_upload_path)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
